name: Currency Bot

on:
  schedule:
    - cron: "0 * * * *"   # запуск каждый час
  workflow_dispatch:       # можно запустить руками

jobs:
  update-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests python-telegram-bot==13.15

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}
        run: python bot.py
