name: Daily Weather

on:
  schedule:
    # 09:00 Europe/Belgrade — GitHub schedules run in UTC, so use 07:00 or 08:00 depending on DST.
    - cron: '07 7 * * *'
  workflow_dispatch: {}

jobs:
  send-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-telegram-bot

      - name: Send Novi Sad weather
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python weather.py
